### ISSUE TITLE
readme copyright

### ISSUE THREAD

**Issue by laramartin** [justodepp/NewsFeedApp#1]
I saw you forked my project (https://github.com/laramartin/android_newsfeed) and then removed the fork, but copied the entire readme file.

For your info, in Germany this is illegal. I didn't specify any license, which means the code belongs to me and you will be reported to Github and Udacity.

**Comment by justodepp** [comment]
Just for a readme file?
No problem, if is not right what I do (using some words of your readme file) I'll remove all the txt content.

Anyway you are talking of "which means the code belongs to me", but the problem  it's the readme file not the code created.


Specify the problem please.
